version: "3.9"

services:
  # Serviço que irá rodar o node
  backend:
    container_name: docker-node-mongo
    build: .
    ports:
    - 3003:3003
    links:
    - mongodb
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      # Garanta que não haverá conflitos de porta com um mongodb que esteja
      # rodando localmente
      - 27017:27017
